#!/bin/bash

SERVICES="ssh"
DAEMON="xivo-sysconfd"

function start {
    for service in $SERVICES
    do
        echo "Launch $service ..."
        service $service start
    done
}

function config_prov {
    PROV_FILENAME=${AMID_CONF_NAME:-"$DAEMON.yml"}
    if [ ! -z $PROV_URL ]
    then
        echo "Provisioning config file $PROV_FILENAME from $PROV_URL"
        curl $PROV_URL/$PROV_FILENAME -o /etc/xivo/$DAEMON/$DAEMON.yml
    fi
}

function show_ip {
    IP=$(ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}')
    echo "The container IP is : " $IP
}

# Launching daemon
start
config_prov
show_ip
$DAEMON -l debug -f
