#!/bin/bash

SERVICES="ssh"

function start {
    for service in $SERVICES
    do
        echo "Launch $service ..."
        service $service start
    done
}

# Launching xivo-sysconfd
start
xivo-sysconfd -d -f
